import { PRODUCT_NAME } from "../shared/brand-defaults";

/** DES-2 brand raster paths (generated by `npm run generate:brand`). */
export const BRAND_LOGO = {
  navWordmark: "/brand/wordmark-dark/wordmark-dark-380w.png",
  navWordmark2x: "/brand/wordmark-dark/wordmark-dark-760w.png",
  mark512: "/brand/mark-app/mark-512.png",
  marketingWordmark: "/brand/wordmark-dark/wordmark-dark-1520w.png",
  marketingTitleCard: "/brand/marketing/title-card-1920x1080-dark.png",
  marketingMarkOverlay: "/brand/mark-transparent/mark-transparent-512w.png",
} as const;

export function brandWordmarkImgHtml(className = "mkt-logo-img"): string {
  const { navWordmark, navWordmark2x } = BRAND_LOGO;
  return `<img src="${navWordmark}" srcset="${navWordmark} 1x, ${navWordmark2x} 2x" alt="${PRODUCT_NAME}" width="190" height="48" class="${className}" decoding="async" />`;
}
